//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netly.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class netlyEntities : DbContext
    {
        public netlyEntities()
            : base("name=netlyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApiKey> ApiKeys { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<UrlAggregate> UrlAggregates { get; set; }
        public virtual DbSet<UrlHistory> UrlHistories { get; set; }
        public virtual DbSet<UrlMap> UrlMaps { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UrlHistoryDetailView> UrlHistoryDetailViews { get; set; }
        public virtual DbSet<UrlMapDetailView> UrlMapDetailViews { get; set; }
    }
}
