//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlAggregate
    {
        public int Id { get; set; }
        public string UrlHash { get; set; }
        public string AggregateUrl { get; set; }
        public string LongUrl { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public string ContentType { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string AddedBy { get; set; }
    }
}
