//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlMapDetailView
    {
        public int Id { get; set; }
        public string ShortUrl { get; set; }
        public string CustomUrl { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string AddedBy { get; set; }
        public string UrlHash { get; set; }
        public string LongUrl { get; set; }
        public string Title { get; set; }
        public Nullable<int> Clicks { get; set; }
        public Nullable<int> TotalClicks { get; set; }
    }
}
